export const CHANGE_CURRENT_DRAW_TYPE = "CHANGE_CURRENT_DRAW_TYPE";
export const CHANGE_ZOOM = "CHANGE_ZOOM";
export const SET_SELECT_SHAPE = "SET_SELECT_SHAPE";
export const UPDATE_DRAW_OBJET = "UPDATE_DRAW_OBJET";
export const CREATE_DRAW_OBJECT = "CREATE_DRAW_OBJECT";
export const CHANGE_CURRENT_DRAW_STATE = "CHANGE_CURRENT_DRAW_STATE";
export const DELETE_DRAW_OBJECT = "DELETE_DRAW_OBJECT";
export const RESET_CURRENT_STATE_DRAW_OBJECT =
  "RESET_CURRENT_STATE_DRAW_OBJECT";
export const UPDATE_LABEL_OF_DRAW_OBJECT = "UPDATE_LABEL_OF_DRAW_OBJECT";
export const UNDO_DRAW_OBJECT = "UNDO_DRAW_OBJECT";
export const REDO_DRAW_OBJECT = "REDO_DRAW_OBJECT";
