import { asyncAction } from "utils/general";

export const CHANGE_PREPROCESSING_EXPERT_MODE =
  "CHANGE_PREPROCESSING_EXPERT_MODE";
export const CHANGE_REFERENCE_PREPROCESSING_IMAGE =
  "CHANGE_REFERENCE_PREPROCESSING_IMAGE";
export const SET_REFERENCE_SELECTOR_DIALOG = "SET_REFERENCE_SELECTOR_DIALOG";
export const SET_SELECTED_METHODS = "SET_SELECTED_METHODS";
export const GENERATE_REFERENCE_IMAGES = asyncAction(
  "GENERATE_REFERENCE_IMAGES"
);
export const FETCH_REFERENCE_IMAGE_INFO = asyncAction(
  "FETCH_REFERENCE_IMAGE_INFO"
);
export const RESET_STATE_GENERATE_REFERENCE_IMAGE =
  "RESET_STATE_GENERATE_REFERENCE_IMAGE";
export const UPDATE_IS_ABLE_TO_RUN_PREPROCESS_ERROR =
  "UPDATE_IS_ABLE_TO_RUN_PREPROCESS_ERROR";
