export const CHANGE_PREPROCESSING_EXPERT_MODE =
  "CHANGE_PREPROCESSING_EXPERT_MODE";

export const CHANGE_REFERENCE_PREPROCESSING_IMAGE =
  "CHANGE_REFERENCE_PREPROCESSING_IMAGE";

export const SET_REFERENCE_SELECTOR_DIALOG = "SET_REFERENCE_SELECTOR_DIALOG";
