/* eslint-disable import/no-cycle */
import {
  PREPROCESS_TASK_PROCESS_TYPE,
  AUGMENT_TASK_PROCESS_TYPE,
  UPLOAD_TASK_PROCESS_TYPE,
  DOWNLOAD_TASK_PROCESS_TYPE,
  HEALTHCHECK_TASK_PROCESS_TYPE,
  RUNNING_TASK_STATUS,
  FINISH_TASK_STATUS,
  ERROR_TASK_STATUS,
  // FILTER_ALL_TASK_PROCESS_TYPE,
  FILTER_ALL_TASK_STATUS,
} from "./defaultValues";

export type TaskProcessType =
  | typeof PREPROCESS_TASK_PROCESS_TYPE
  | typeof AUGMENT_TASK_PROCESS_TYPE
  | typeof UPLOAD_TASK_PROCESS_TYPE
  | typeof DOWNLOAD_TASK_PROCESS_TYPE
  | typeof HEALTHCHECK_TASK_PROCESS_TYPE;
// | typeof FILTER_ALL_TASK_PROCESS_TYPE;

export type TaskStatusMergedType =
  | typeof RUNNING_TASK_STATUS
  | typeof FINISH_TASK_STATUS
  | typeof ERROR_TASK_STATUS
  | typeof FILTER_ALL_TASK_STATUS;
