export const ADDED_UPLOAD_FILE_STATUS = "ADDED_UPLOAD_FILE_STATUS";
export const CHECKING_UPLOAD_FILE_STATUS = "CHECKING_UPLOAD_FILE_STATUS";
export const QUEUEING_UPLOAD_FILE_STATUS = "QUEUEING_UPLOAD_FILE_STATUS";
export const UPLOADING_UPLOAD_FILE_STATUS = "UPLOADING_UPLOAD_FILE_STATUS";
export const UPLOADED_UPLOAD_FILE_STATUS = "UPLOADED_UPLOAD_FILE_STATUS";
export const FAILED_UPLOAD_FILE_STATUS = "FAILED_UPLOAD_FILE_STATUS";
export const CHECK_ZIP_FILE = "CHECK_ZIP_FILE";
export const INVALID_FILE_STATUS = "INVALID_FILE_STATUS";
