export const SET_FEEDBACK_CONTENT = "SET_FEEDBACK_CONTENT";
export const SET_FEEDBACK_ATTACHMENT = "SET_FEEDBACK_ATTACHMENT";
export const RESET_FEEDBACK = "RESET_FEEDBACK";
export const DELETE_FEEDBACK_ATTACHMENT = "DELETE_FEEDBACK_ATTACHMENT";
export const UPDATE_FEEDBACK_PROCESSING_STATUS =
  "UPDATE_FEEDBACK_PROCESSING_STATUS";
