import { asyncAction } from "utils/general";

export const CHANGE_AUGMENTATION_EXPERT_MODE =
  "CHANGE_AUGMENTATION_EXPERT_MODE";

export const CHANGE_REFERENCE_AUGMENTATION_IMAGE =
  "CHANGE_REFERENCE_AUGMENTATION_IMAGE";

export const SET_REFERENCE_AUGMENTATION_SELECTOR_DIALOG =
  "SET_REFERENCE_AUGMENTATION_SELECTOR_DIALOG";

export const GET_AUGMENT_CUSTOM_METHOD_PREVIEW_IMAGE_INFO = asyncAction(
  "GET_AUGMENT_CUSTOM_METHOD_PREVIEW_IMAGE_INFO"
);

export const CHANGE_AUGMENT_CUSTOM_METHOD_PARAM_VALUE =
  "CHANGE_AUGMENT_CUSTOM_METHOD_PARAM_VALUE";

export const ADD_AUGMENT_CUSTOM_METHOD_PARAM_VALUE =
  "ADD_AUGMENT_CUSTOM_METHOD_PARAM_VALUE";

export const REMOVE_AUGMENT_CUSTOM_METHOD_PARAM_VALUE =
  "REMOVE_AUGMENT_CUSTOM_METHOD_PARAM_VALUE";

export const CHANGE_IS_LOADING_AUGMENT_CUSTOM_METHOD_PREVIEW_IMAGE =
  "CHANGE_IS_LOADING_AUGMENT_CUSTOM_METHOD_PREVIEW_IMAGE";
