import { asyncAction } from "utils/general";

export const CHANGE_AUGMENTATION_EXPERT_MODE =
  "CHANGE_AUGMENTATION_EXPERT_MODE";

export const CHANGE_REFERENCE_AUGMENTATION_IMAGE =
  "CHANGE_REFERENCE_AUGMENTATION_IMAGE";

export const SET_REFERENCE_AUGMENTATION_SELECTOR_DIALOG =
  "SET_REFERENCE_AUGMENTATION_SELECTOR_DIALOG";

export const SET_AUGMENTATION_SELECTED_METHOD =
  "SET_AUGMENTATION_SELECTED_METHOD";

export const GET_AUGMENT_CUSTOM_METHOD_PREVIEW_IMAGE_INFO = asyncAction(
  "GET_AUGMENT_CUSTOM_METHOD_PREVIEW_IMAGE_INFO"
);

export const CHANGE_AUGMENT_CUSTOM_METHOD_PARAM_VALUE =
  "CHANGE_AUGMENT_CUSTOM_METHOD_PARAM_VALUE";
