export const CHANGE_AUGMENTATION_EXPERT_MODE =
  "CHANGE_AUGMENTATION_EXPERT_MODE";

export const CHANGE_REFERENCE_AUGMENTATION_IMAGE =
  "CHANGE_REFERENCE_AUGMENTATION_IMAGE";

export const SET_REFERENCE_AUGMENTATION_SELECTOR_DIALOG =
  "SET_REFERENCE_AUGMENTATION_SELECTOR_DIALOG";
