import { asyncAction } from "utils/general";

export const SET_IS_OPEN_CREATE_PROJECT_MODAL =
  "SET_IS_OPEN_CREATE_PROJECT_MODAL";

export const CREATE_PROJECT = asyncAction("CREATE_PROJECT");
export const FETCH_LIST_PROJECTS = asyncAction("FETCH_LIST_PROJECTS");
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const UPDATE_STATISTIC_PROJECT = "UPDATE_STATISTIC_PROJECT";
export const FETCH_DETAIL_PROJECT = asyncAction("FETCH_DETAIL_PROJECT");
export const FETCH_METHOD_LIST = asyncAction("FETCH_METHOD_LIST");
export const FETCH_PROJECT_TASK_LIST = asyncAction("FETCH_PROJECT_TASK_LIST");
export const FETCH_TASK_INFO = asyncAction("FETCH_TASK_INFO");
export const SET_SPLIT_DATA_NUMBER = "SET_SPLIT_DATA_NUMBER";
export const CHANGE_SELECTED_DATA_SOURCE = "CHANGE_SELECTED_DATA_SOURCE";
export const CREATE_SAMPLE_PROJECT = asyncAction("CREATE_SAMPLE_PROJECT");
export const DELETE_PROJECT = asyncAction("DELETE_PROJECT");
export const LOAD_PROJECT_THUMBNAIL_IMAGE = asyncAction(
  "LOAD_PROJECT_THUMBNAIL_IMAGE"
);
export const SET_IS_OPEN_DELETE_CONFIRM = "SET_IS_OPEN_DELETE_CONFIRM";
export const SET_IS_EDITING_SPLIT_DATA = "SET_IS_EDITING_SPLIT_DATA";

export const EMPTY_SPLIT_DATA_NUMBER = [0, 0, 0];
