export const SET_PAGE_LOADING = "SET_PAGE_LOADING";

export const GENERATE_S3_CLIENT = "GENERATE_S3_CLIENT";
export const EMPTY_S3_CLIENT = "EMPTY_S3_CLIENT";
export const SET_IS_CHECKING_APP = "SET_IS_CHECKING_APP";
