import { asyncAction } from "utils/general";

export const ADD_IMAGES = "ADD_IMAGES";
export const CHANGE_PREVIEW_IMAGE = "CHANGE_PREVIEW_IMAGE";
export const SAVE_ANNOTATION_STATE_MANAGER = asyncAction(
  "SAVE_ANNOTATION_STATE_MANAGER"
);
export const SET_ANNOTATION_STATE_MANAGER = "SET_ANNOTATION_STATE_MANAGER";
export const ADD_NEW_CLASS_LABEL = "ADD_NEW_CLASS_LABEL";
export const EDIT_CLASS_LABEL = "EDIT_CLASS_LABEL";
export const SET_CLASS_MANAGE_MODAL = "SET_CLASS_MANAGE_MODAL";
export const EDIT_CLASS_MANAGE_MODAL = "EDIT_CLASS_MANAGE_MODAL";
export const FETCH_FILE_AND_ANNOTATION = asyncAction(
  "FETCH_FILE_AND_ANNOTATION"
);
