import { asyncAction } from "utils/general";

export const ADD_IMAGES = "ADD_IMAGES";
export const CHANGE_PREVIEW_IMAGE = asyncAction("CHANGE_PREVIEW_IMAGE");
export const SET_PREVIEW_IMAGE = "SET_PREVIEW_IMAGE";
export const SAVE_ANNOTATION_STATE_MANAGER = asyncAction(
  "SAVE_ANNOTATION_STATE_MANAGER"
);
export const SET_ANNOTATION_STATE_MANAGER = "SET_ANNOTATION_STATE_MANAGER";
export const ADD_NEW_CLASS_LABEL = "ADD_NEW_CLASS_LABEL";
export const EDIT_CLASS_LABEL = "EDIT_CLASS_LABEL";
export const SET_CLASS_MANAGE_MODAL = "SET_CLASS_MANAGE_MODAL";
export const EDIT_CLASS_MANAGE_MODAL = "EDIT_CLASS_MANAGE_MODAL";
export const FETCH_FILE_AND_ANNOTATION = asyncAction(
  "FETCH_FILE_AND_ANNOTATION"
);
export const SAVE_REMOTE_NEW_CLASS_LABEL = asyncAction("SAVE_NEW_CLASS_LABEL");
export const RESET_ANNOTATION_MANAGER = "RESET_ANNOTATION_MANAGER";
export const SET_CLIENT_RECT_OF_BASE_IMAGE = "SET_CLIENT_RECT_OF_BASE_IMAGE";
